name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Nexus
        uses: docker/login-action@v2
        with:
          registry: cr.alkhwarizmi.online
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t cr.alkhwarizmi.online/testrepo:latest ./Practice2

      - name: Push Docker image
        run: |
          docker push cr.alkhwarizmi.online/testrepo:latest
